// <auto-generated />
namespace webacademy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class adTable_employees : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adTable_employees));
        
        string IMigrationMetadata.Id
        {
            get { return "201501200536351_adTable_employees"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
