// <auto-generated />
namespace webacademy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addTables_Employees_Skills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTables_Employees_Skills));
        
        string IMigrationMetadata.Id
        {
            get { return "201501200551592_addTables_Employees_Skills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
